enum
{
    SOUND_FOLDER_META = 1,
    SOUND_FOLDER_SPACE = 2,
    SOUND_FOLDER_SHAKE = 3,
    SOUND_FOLDER_SIMON = 4,
};

enum
{
    SOUND_META_BEEP0 = 1,
    SOUND_META_BEEP1 = 2,
    SOUND_META_ARMED = 3,
    SOUND_META_EXPLODE = 4,
    SOUND_META_FAIL = 5,
    SOUND_META_DEFUSE = 6,
    SOUND_META_WIN = 7,
    SOUND_META_GAME_WIN = 8,
    SOUND_META_GAME_LOSE = 9,
};

enum
{
    SOUND_SPACE_MENU = 1,
    SOUND_SPACE_UP = 2,
    SOUND_SPACE_DOWN = 3,
    SOUND_SPACE_CRASH = 4,
};

enum
{
    SOUND_SHAKE_LOSS_TONES_START = 1,
    SOUND_SHAKE_LOSS_TONES_END = SOUND_SHAKE_LOSS_TONES_START + 16,

    SOUND_SHAKE_WIN_TONES_START = 18,
    SOUND_SHAKE_WIN_TONES_END = SOUND_SHAKE_WIN_TONES_START + 16,
};

enum
{
    // 0-9 = numbers, 10 = *, 11 = #
    SOUND_SIMON_TONES_START = 1,
    SOUND_SIMON_TONES_END = SOUND_SIMON_TONES_START + 18,

    SOUND_SIMON_CORRECT = 20,
    SOUND_SIMON_INCORRECT = 21,
};