enum
{
    SOUND_FOLDER_META = 1,
    SOUND_FOLDER_SPACE = 2,
    SOUND_FOLDER_SHAKE = 3,
    SOUND_FOLDER_SIMON = 4,
};

enum
{
    SOUND_META_BEEP0 = 1,
    SOUND_META_BEEP1 = 2,
    SOUND_META_ARMED = 3,
    SOUND_META_CONFIRM = 4,
    SOUND_META_EXPLODE = 5,
    SOUND_META_FAIL = 6,
    SOUND_META_DEFUSE = 7,
    SOUND_META_WIN = 8,
};

enum
{
    SOUND_SPACE_MENU = 1,
    SOUND_SPACE_UP = 2,
    SOUND_SPACE_DOWN = 3,
    SOUND_SPACE_CRASH = 4,
};

enum
{
    SOUND_SHAKE_LOSS_TONES_START = 1,
    SOUND_SHAKE_LOSS_TONES_END = 1 + 16,

    SOUND_SHAKE_WIN_TONES_START = 1,
    SOUND_SHAKE_WIN_TONES_END = 1 + 16,
};